services:
  jenkinsadmin:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: jenkins_server
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_data:/var/jenkins_home

  jenkinsagent1:
    image: jenkins/agent
    container_name: jenkins_agent_1
    restart: on-failure
    depends_on:
      - jenkinsadmin

  jenkinsagent2:
    image: jenkins/agent
    container_name: jenkins_agent_2
    restart: on-failure
    depends_on:
      - jenkinsadmin

volumes:
  jenkins_data: